version: '3.5'
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: chat
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-p12345678", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5


  migration:
    build: .
    command: bash -c "python manage.py makemigrations chat && python manage.py migrate"
    volumes:
      - .:/django_chat_room
    depends_on:
      - db

  app:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/django_chat_room
    depends_on:
      - redis
      - db

volumes:
  redis-data:
  mysql_data:
